// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXtXleMQEH6y3sI8G-OJ6YLbrqobUWGtI',
    appId: '1:747351579106:web:79561c3857af20102081bb',
    messagingSenderId: '747351579106',
    projectId: 'portfolio-2b19f',
    authDomain: 'portfolio-2b19f.firebaseapp.com',
    storageBucket: 'portfolio-2b19f.appspot.com',
    measurementId: 'G-918FRV1J52',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNCMQDF5uzE0coKKMtfKto3ZBeumn7PL4',
    appId: '1:747351579106:android:7d69ab7d463c725b2081bb',
    messagingSenderId: '747351579106',
    projectId: 'portfolio-2b19f',
    storageBucket: 'portfolio-2b19f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfEdNCtVqE3YLsmEcsg06bykibcupWfKM',
    appId: '1:747351579106:ios:55e2f98275fcfde62081bb',
    messagingSenderId: '747351579106',
    projectId: 'portfolio-2b19f',
    storageBucket: 'portfolio-2b19f.appspot.com',
    iosClientId: '747351579106-ovh52bfttvvnabl74kqi3gr9ul0rj4l2.apps.googleusercontent.com',
    iosBundleId: 'com.example.portfolio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDfEdNCtVqE3YLsmEcsg06bykibcupWfKM',
    appId: '1:747351579106:ios:55e2f98275fcfde62081bb',
    messagingSenderId: '747351579106',
    projectId: 'portfolio-2b19f',
    storageBucket: 'portfolio-2b19f.appspot.com',
    iosClientId: '747351579106-ovh52bfttvvnabl74kqi3gr9ul0rj4l2.apps.googleusercontent.com',
    iosBundleId: 'com.example.portfolio',
  );
}
